-- Calendar dimension: one row per day across a FIXED span (var date_spine_start
-- .. date_spine_end, end exclusive), generated by dbt_date.get_base_dates, plus
-- two sentinel "eternity" rows just outside the spine -- past_eternity (var,
-- 1900-01-01) and future_eternity (var, 9999-01-01). Those give an unknown /
-- not-applicable date reference a real calendar row to point at instead of NULL
-- (so its dim_date relationships test still passes). This dimension depends on
-- no other model to build -- the corpus-coverage guarantee lives in
-- assert_dim_date_covers_corpus, which fails the build if the data ever outgrows
-- the fixed span (widen the var when it does). Facts store the calendar DATE and
-- join on date_day; there is no separate integer date key.
-- Grain = date_day. -> ../data/derived/dim_date.csv
WITH all_days AS (
  SELECT
    base.date_day::DATE AS date_day,
    false AS is_synthetic_row
  FROM (
    {{ dbt_date.get_base_dates(
        start_date=var('date_spine_start'),
        end_date=var('date_spine_end')
    ) }}
  ) AS base
  -- the two "eternity" sentinels are synthetic rows just outside the real spine
  UNION ALL
  SELECT DATE '{{ var('past_eternity') }}' AS date_day, true AS is_synthetic_row
  UNION ALL
  SELECT DATE '{{ var('future_eternity') }}' AS date_day, true AS is_synthetic_row
)

SELECT
  all_days.date_day,
  YEAR(all_days.date_day) AS year_num,
  QUARTER(all_days.date_day) AS quarter_num,
  MONTH(all_days.date_day) AS month_num,
  MONTHNAME(all_days.date_day) AS month_name,
  DAY(all_days.date_day) AS day_of_month,
  ISODOW(all_days.date_day) AS iso_dow,
  DAYNAME(all_days.date_day) AS weekday_name,
  ISODOW(all_days.date_day) < 6 AS is_weekday,
  all_days.is_synthetic_row
FROM all_days
