-- Calendar dimension: one row per day across a FIXED span (var date_spine_start
-- .. date_spine_end, end exclusive). The spine is generated by
-- dbt_date.get_base_dates, so this dimension depends on no other model to build
-- -- the corpus-coverage guarantee it used to derive its own bounds from now
-- lives in assert_dim_date_covers_corpus, which fails the build if the data
-- ever outgrows the fixed span (widen the var when it does). Facts store the
-- calendar DATE and join on date_day -- there is no separate integer date key.
-- Grain = date_day (one row per day). -> ../data/derived/dim_date.csv
SELECT
  base.date_day::DATE AS date_day,
  YEAR(base.date_day) AS year_num,
  QUARTER(base.date_day) AS quarter_num,
  MONTH(base.date_day) AS month_num,
  MONTHNAME(base.date_day) AS month_name,
  DAY(base.date_day) AS day_of_month,
  ISODOW(base.date_day) AS iso_dow,
  DAYNAME(base.date_day) AS weekday_name,
  ISODOW(base.date_day) < 6 AS is_weekday
FROM (
  {{ dbt_date.get_base_dates(
      start_date=var('date_spine_start'),
      end_date=var('date_spine_end')
  ) }}
) AS base
