# pyright: strict
"""sources.ai_involvement: the pure helpers behind the AI-involvement classifier
models (the Ollama call itself is network I/O and isn't unit-tested here)."""

import pytest

from pg_analysis.sources.ai_involvement import (
    AI_PROMPT_VERSION,
    DISCLOSURE_FORMS,
    LABEL_COLS,
    OUTPUT_COLS,
    ROLE_FLAGS,
    VENDORS,
    AiLabel,
    ai_content_hash,
    as_bool,
    build_ai_schema,
    evidence_field,
    hint_lines,
    label_rows,
    label_to_cells,
    parse_ai_label,
    roles_prompt,
)
from pg_analysis.sources.classify import content_hash


def _answer(**overrides: object) -> dict[str, object]:
    base: dict[str, object] = {
        "ai_mentions": "Claude Code",
        "found_evidence": "Reported-by: Claude Code (via Noah Misch)",
        "ai_found": True,
        "analyzed_evidence": "none",
        "ai_analyzed": False,
        "authored_evidence": "none",
        "ai_authored": False,
        "tooling_evidence": "none",
        "ai_tooling": False,
        "mentioned_only": False,
        "vendor": "anthropic",
        "disclosure_form": "trailer",
        "confidence": 0.9,
    }
    return {**base, **overrides}


def test_ai_content_hash_is_keyed_on_the_ai_prompt_version() -> None:
    assert ai_content_hash("t", "m") == content_hash("t", "m", AI_PROMPT_VERSION)
    assert ai_content_hash("t", "m") != content_hash("t", "m")  # not the content-taxonomy key


def test_roles_prompt_orders_by_role_order() -> None:
    block = roles_prompt([(2, "b", "second"), (1, "a", "first")])
    assert block == "1. a — first\n2. b — second"


def test_build_ai_schema_lists_mentions_then_evidence_before_each_flag() -> None:
    schema = build_ai_schema()
    keys = list(schema["properties"])
    assert keys[0] == "ai_mentions"
    for flag in ROLE_FLAGS[:4]:  # each work role's evidence comes right before its flag
        assert keys.index(flag) == keys.index(evidence_field(flag)) + 1
    assert keys[-4:] == ["mentioned_only", "vendor", "disclosure_form", "confidence"]
    assert schema["properties"]["vendor"]["enum"] == list(VENDORS)
    assert schema["properties"]["disclosure_form"]["enum"] == list(DISCLOSURE_FORMS)
    assert schema["required"] == keys


def test_parse_ai_label_reads_flags_and_builds_the_rationale_from_set_roles() -> None:
    label = parse_ai_label(_answer(ai_mentions="  Claude\n Code ", confidence=1.7))
    assert label.ai_found is True
    assert label.mentioned_only is False
    assert label.vendor == "anthropic"
    assert label.disclosure_form == "trailer"
    assert label.confidence == 1.0  # clamped
    # squashed mention list, then only the SET roles' evidence
    assert label.rationale == "mentions: Claude Code | found: Reported-by: Claude Code (via Noah Misch)"


def test_parse_ai_label_lets_a_work_role_win_over_mentioned_only() -> None:
    label = parse_ai_label(_answer(mentioned_only=True))
    assert label.ai_found is True
    assert label.mentioned_only is False
    only = parse_ai_label(_answer(ai_found=False, mentioned_only=True, disclosure_form="prose"))
    assert only.mentioned_only is True


def test_parse_ai_label_rejects_out_of_enum_values() -> None:
    with pytest.raises(ValueError, match="out-of-enum"):
        parse_ai_label(_answer(vendor="acme"))
    with pytest.raises(ValueError, match="out-of-enum"):
        parse_ai_label(_answer(disclosure_form="footnote"))


def test_label_to_cells_matches_label_cols_layout() -> None:
    label = AiLabel(True, False, True, False, False, "openai", "prose", 0.75, "drafted with Codex")
    cells = label_to_cells(label)
    assert len(cells) == len(LABEL_COLS) - 3  # after content_hash, model, prompt_version
    assert cells == ["true", "false", "true", "false", "false", "openai", "prose", "0.75", "drafted with Codex"]


def test_hint_lines_points_at_ai_words_but_not_ordinary_ones() -> None:
    text = (
        "Fix a cursor bug.\n\nI used a  simple benchmark script generated by LLM.\n"
        "The planner model was wrong.\nReported-by: Claude Code (via Noah Misch)\n"
        "See https://wiki.postgresql.org/?utm_source=chatgpt.com\n"
    )
    hints = hint_lines(text)
    assert hints == [
        "I used a simple benchmark script generated by LLM.",  # whitespace squashed
        "Reported-by: Claude Code (via Noah Misch)",
        "See https://wiki.postgresql.org/?utm_source=chatgpt.com",  # hinted, the model judges it
    ]
    assert hint_lines("no cursor, model or agent words count") == []


def test_as_bool_reads_csv_and_python_booleans() -> None:
    assert as_bool(True) is True
    assert as_bool("true") is True
    assert as_bool(" True ") is True
    assert as_bool("false") is False
    assert as_bool(None) is False


def test_label_rows_reuses_the_cache_and_classifies_only_new_text() -> None:
    label = AiLabel(False, True, False, False, False, "anthropic", "prose", 0.8, "asked Claude to confirm")
    calls: list[str] = []

    def fake(text: str) -> AiLabel:
        calls.append(text)
        return label

    cached_hash = ai_content_hash("old text", "m")
    cache = {
        cached_hash: [
            cached_hash,
            "m",
            AI_PROMPT_VERSION,
            "true",
            "false",
            "false",
            "false",
            "false",
            "openai",
            "trailer",
            "0.90",
            "cached",
        ]
    }
    rows = label_rows([(("k1",), "old text"), (("a", "b"), "new text")], cache, "m", fake)
    assert calls == ["new text"]
    assert rows[0] == [
        "k1",
        cached_hash,
        "m",
        AI_PROMPT_VERSION,
        "true",
        "false",
        "false",
        "false",
        "false",
        "openai",
        "trailer",
        "0.90",
        "cached",
        True,  # is_classified
    ]
    assert rows[1][:2] == ["a", "b"]
    assert rows[1][2] == ai_content_hash("new text", "m")
    assert rows[1][3:5] == ["m", AI_PROMPT_VERSION]
    assert rows[1][5:-1] == label_to_cells(label)
    assert rows[1][-1] is True


def test_label_rows_cached_only_mode_marks_unseen_text_unclassified() -> None:
    cached_hash = ai_content_hash("old text", "m")
    cells = [
        cached_hash,
        "m",
        AI_PROMPT_VERSION,
        "true",
        "false",
        "false",
        "false",
        "false",
        "openai",
        "trailer",
        "0.90",
        "cached",
    ]
    items = [(("k1",), "old text"), *[((str(i),), f"new {i}") for i in range(5)]]
    # classify=None: no call, no max_inline error even though 5 > 2, NULL labels
    rows = label_rows(items, {cached_hash: cells}, "m", None, max_inline=2)
    assert len(rows) == 6
    assert all(len(row) == 1 + len(OUTPUT_COLS) for row in rows)
    assert rows[0][-1] is True
    unseen = rows[1]
    assert unseen[:2] == ["0", ai_content_hash("new 0", "m")]
    assert unseen[2:4] == ["m", AI_PROMPT_VERSION]
    assert unseen[4:-1] == [None] * (len(LABEL_COLS) - 3)
    assert unseen[-1] is False


def test_label_rows_refuses_a_bulk_inline_job() -> None:
    def never(text: str) -> AiLabel:
        raise AssertionError(text)

    items = [((str(i),), f"text {i}") for i in range(3)]
    with pytest.raises(RuntimeError, match="backfill_ai_involvement"):
        label_rows(items, {}, "m", never, max_inline=2)
